### PR TITLE
Use Vultr API v2

### PR DESCRIPTION
**Pull request by kjoyce77**
#1 
Note: I used version 1.1.0rc1.  I don't know if you prefer 1.1.0 or 1.0.4 so didn't want to give it an official version until you build it.

I have tested this on my own domains.

### CODE REVIEW

**Comment by lezgomatt** [comment]
Hey @kjoyce77, this is great! Thank you so much for your contribution! 😄 

> Note: I used version 1.1.0rc1. I don't know if you prefer 1.1.0 or 1.0.4 so didn't want to give it an official version until you build it.

Sounds good to me. I'll update this to `1.1.0` after testing it on my domains (hopefully sometime this week).

**Comment by ugjka** [comment]
When all is tested and done don't forget to push it to PyPI (or does happen automatically? not a python guy...)

**Comment by lezgomatt** [comment]
It's not automatic (although you probably could automate it with GitHub actions). I already pushed `1.1.0rc1` (https://pypi.org/project/certbot-dns-vultr/1.1.0rc1/), but since it's a pre-release it's not selected by default.

Will test this out myself and update the readme this weekend before releasing `1.1.0` .

**Comment by ugjka** [comment]
Upgraded to --pre, Tested on my domains, seemed to work

**Pull request merged**
